-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 15:51:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`editions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL COMMENT 'название издания',
  `description` VARCHAR(255) NULL COMMENT 'описание издания',
  `price_per_month` DECIMAL(5,2) NULL COMMENT 'цена за 1 в месяц',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'перечень изданий';


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL COMMENT 'фамилия, имя',
  `email` VARCHAR(255) NULL COMMENT 'электронная почта',
  `password` VARCHAR(10) NOT NULL COMMENT 'пароль',
  `admin` TINYINT NOT NULL COMMENT 'признак (admin)',
  PRIMARY KEY (`id`))
COMMENT = 'пользователи';


-- -----------------------------------------------------
-- Table `mydb`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`applications` (
  `id` INT NOT NULL,
  `date` DATE NULL COMMENT 'дата подписки',
  `user_id` INT NULL COMMENT 'подписчик',
  PRIMARY KEY (`id`),
  INDEX `user_id_fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'подписка';


-- -----------------------------------------------------
-- Table `mydb`.`black_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`black_list` (
  `id` INT NOT NULL,
  `user_id` INT NULL COMMENT 'id подпищика',
  `applications_id` INT NULL COMMENT 'id подписки',
  PRIMARY KEY (`id`),
  CONSTRAINT `aplication_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'черный список подпищиков';


-- -----------------------------------------------------
-- Table `mydb`.`list_editions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`list_editions` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'список подписок с количеством месяцев ',
  `number_of_months` INT NULL COMMENT 'количество месяцев подписки',
  `editions_id` INT NULL COMMENT 'id издания',
  `applications_id` INT NULL COMMENT 'id подписки',
  PRIMARY KEY (`id`),
  INDEX `fk_editions_has_applications_applications1_idx` (`applications_id` ASC) VISIBLE,
  INDEX `fk_editions_has_applications_editions1_idx` (`editions_id` ASC) VISIBLE,
  CONSTRAINT `fk_editions_has_applications_editions1`
    FOREIGN KEY (`editions_id`)
    REFERENCES `mydb`.`editions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_editions_has_applications_applications1`
    FOREIGN KEY (`applications_id`)
    REFERENCES `mydb`.`applications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'список изданий который выбрал подписчик';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
